import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { resolveVaultPaths, sha256, shortId, slugify } from "./paths.js";
import { NotvaState } from "./state.js";
import type { PageRecord, ProposalRecord, SourceRecord } from "./types.js";

export interface ProposeMissingWikiLinksOptions {
  root: string;
}

export interface MissingWikiLinkSuggestion {
  path: string;
  title: string;
  targets: Array<{ path: string; title: string }>;
}

export interface ProposeMissingWikiLinksResult {
  created: boolean;
  proposal?: ProposalRecord;
  suggestions: MissingWikiLinkSuggestion[];
}

export async function proposeMissingWikiLinks(options: ProposeMissingWikiLinksOptions): Promise<ProposeMissingWikiLinksResult> {
  const paths = resolveVaultPaths(options.root);
  const now = new Date().toISOString();
  const state = new NotvaState(paths.stateDb);
  try {
    state.initialize();
    const pages = state.listPages();
    const suggestions = findMissingWikiLinkSuggestions(pages);
    if (suggestions.length === 0) return { created: false, suggestions };

    const proposalId = proposalIdForSuggestions(suggestions);
    const existing = state.getProposal(proposalId);
    if (existing?.status === "pending") {
      return { created: false, proposal: existing, suggestions };
    }

    const sourceBody = renderSuggestionSource(suggestions);
    const sourceId = shortId(`missing-wiki-links-source:${sourceBody}`);
    const rawDir = join(paths.raw, now.slice(0, 10));
    await mkdir(rawDir, { recursive: true });
    const rawPath = join(rawDir, `missing-wiki-links-${sourceId}.md`);
    await writeFile(rawPath, sourceBody, "utf8");

    const source: SourceRecord = {
      id: sourceId,
      kind: "text",
      title: "Missing wiki link suggestions",
      rawPath,
      originalRef: "notva:missing-wiki-links",
      createdAt: now,
      sha256: sha256(sourceBody)
    };
    const pageByPath = new Map(pages.map((page) => [page.path, page]));
    const proposal: ProposalRecord = {
      id: existing ? shortId(`missing-wiki-links-proposal:${proposalId}:${now}`) : proposalId,
      sourceId,
      status: "pending",
      summary: `Add missing wiki links to ${suggestions.length} reviewed page${suggestions.length === 1 ? "" : "s"}.`,
      changes: suggestions.map((suggestion) => {
        const page = pageByPath.get(suggestion.path);
        if (!page) throw new Error(`Page not found while building link proposal: ${suggestion.path}`);
        return {
          type: "update_page" as const,
          path: page.path,
          title: page.title,
          content: renderPageWithMissingLinks(page, suggestion.targets)
        };
      }),
      createdAt: now,
      updatedAt: now
    };

    state.insertSource(source);
    state.insertProposal(proposal);
    return { created: true, proposal, suggestions };
  } finally {
    state.close();
  }
}

export function findMissingWikiLinkSuggestions(pages: PageRecord[]): MissingWikiLinkSuggestion[] {
  return pages.flatMap((page) => {
    const targets = pages
      .filter((target) => target.path !== page.path)
      .filter((target) => mentionsTitle(page.body, target.title))
      .filter((target) => !alreadyLinksTo(page.body, target))
      .sort((a, b) => a.title.localeCompare(b.title))
      .map((target) => ({ path: target.path, title: target.title }));
    return targets.length > 0 ? [{ path: page.path, title: page.title, targets }] : [];
  }).sort((a, b) => a.title.localeCompare(b.title));
}

function mentionsTitle(body: string, title: string): boolean {
  return normalizeText(body).includes(normalizeText(title));
}

function alreadyLinksTo(body: string, target: Pick<PageRecord, "path" | "title">): boolean {
  const title = escapeRegExp(target.title);
  const path = escapeRegExp(target.path);
  return new RegExp(`\\[\\[\\s*${title}(?:[\\]|#]|\\s*\\]\\])`, "i").test(body)
    || new RegExp(`\\]\\((?:\\./)?${path}(?:#[^)]+)?\\)`, "i").test(body);
}

function renderPageWithMissingLinks(page: PageRecord, targets: MissingWikiLinkSuggestion["targets"]): string {
  const bullets = targets.map((target) => `- [[${target.title}]] (${target.path})`).join("\n");
  if (/\n## Related Wiki Pages\s*\n/i.test(page.body)) {
    return page.body.replace(/\n## Related Wiki Pages\s*\n/i, (match) => `${match}\n${bullets}\n`);
  }
  return `${page.body.trimEnd()}\n\n## Related Wiki Pages\n\n${bullets}\n`;
}

function renderSuggestionSource(suggestions: MissingWikiLinkSuggestion[]): string {
  return [
    "# Missing wiki link suggestions",
    "",
    "This source was generated by scanning reviewed Notva wiki pages for exact title mentions that are not yet explicit wiki links.",
    "",
    ...suggestions.flatMap((suggestion) => [
      `## ${suggestion.title}`,
      "",
      `Page: ${suggestion.path}`,
      "Suggested links:",
      ...suggestion.targets.map((target) => `- [[${target.title}]] (${target.path})`),
      ""
    ])
  ].join("\n");
}

function proposalIdForSuggestions(suggestions: MissingWikiLinkSuggestion[]): string {
  return shortId(`missing-wiki-links-proposal:${JSON.stringify(suggestions)}`);
}

function normalizeText(input: string): string {
  return input.replace(/\s+/g, " ").trim().toLocaleLowerCase();
}

function escapeRegExp(input: string): string {
  return input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
