import { readFile } from "node:fs/promises";
import { describe, expect, test } from "vitest";

describe("README", () => {
  test("documents graph, report, web, and Codex install workflows", async () => {
    const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");

    expect(readme).toContain("[中文 README](./README.zh-CN.md)");
    expect(readme).toContain("## Graph Layer");
    expect(readme).toContain("notva graph export");
    expect(readme).toContain("notva graph html");
    expect(readme).toContain("search, filter, and focus");
    expect(readme).toContain("@notva/providers");
    expect(readme).toContain("provider adapter boundaries");
    expect(readme).toContain("local-rule-based");
    expect(readme).toContain("local-noop-embedding");
    expect(readme).toContain("local-substring-search");
    expect(readme).toContain("## Publishing Boundaries");
    expect(readme).toContain("repository root stays private as a workspace guard");
    expect(readme).toContain("The publishable CLI package lives in `packages/cli`");
    expect(readme).toContain("Notva is MIT-licensed");
    expect(readme).toContain("Keep `LICENSE` and package `license` fields aligned");
    expect(readme).toContain("URL ingestion keeps raw HTML");
    expect(readme).toContain("Directory ingestion");
    expect(readme).toContain("code notes");
    expect(readme).toContain("chat logs");
    expect(readme).toContain("JSON chat logs");
    expect(readme).toContain("notva ingest /path/to/notes");
    expect(readme).toContain("Repeated ingestion reuses existing sources and proposals");
    expect(readme).toContain("Related Wiki Pages");
    expect(readme).toContain("[[Wiki Link]]");
    expect(readme).toContain("without making fuzzy inferences");
    expect(readme).toContain("notva links propose");
    expect(readme).toContain("missing wiki links");
    expect(readme).toContain("notva page list");
    expect(readme).toContain("notva page save");
    expect(readme).toContain("notva source list");
    expect(readme).toContain("notva source show");
    expect(readme).toContain("notva source propose");
    expect(readme).toContain("notva source propose --uncovered");
    expect(readme).toContain("promote every raw source without accepted wiki coverage");
    expect(readme).toContain("promote a preserved raw source back into the review queue");
    expect(readme).toContain("default vault path is `~/Notva`");
    expect(readme).toContain("NOTVA_VAULT");
    expect(readme).toContain("raw sources");
    expect(readme).toContain("notva explain <page-or-concept>");
    expect(readme).toContain("notva path <from> <to>");
    expect(readme).toContain("notva report");
    expect(readme).toContain("notva query \"question\" --propose");
    expect(readme).toContain("notva context");
    expect(readme).toContain("notva rules show");
    expect(readme).toContain("notva rules save --content-file");
    expect(readme).toContain("notva status");
    expect(readme).toContain("notva doctor");
    expect(readme).toContain("onboarding and release smoke checks");
    expect(readme).toContain("vault status overview");
    expect(readme).toContain("context pack");
    expect(readme).toContain("schema/*.md");
    expect(readme).toContain("Vault Rules");
    expect(readme).toContain("editable Vault Rules");
    expect(readme).toContain("notva act \"task\" --json");
    expect(readme).toContain("notva act \"task\" --run-actions --json");
    expect(readme).toContain("notva act \"task\" --propose");
    expect(readme).toContain("notva act list");
    expect(readme).toContain("notva act show <id>");
    expect(readme).toContain("notva act propose <id>");
    expect(readme).toContain("act run history");
    expect(readme).toContain("turn a useful act run into a reviewable wiki proposal");
    expect(readme).toContain("notva action run --command");
    expect(readme).toContain("execution plan");
    expect(readme).toContain("ready`, `needs_maintenance`, or `missing_context");
    expect(readme).toContain("Web workbench can run supported maintenance actions");
    expect(readme).toContain("运行并沉淀");
    expect(readme).toContain("整理后运行");
    expect(readme).toContain("生成提案");
    expect(readme).toContain("CLI can run the same allowlisted actions");
    expect(readme).toContain("run suggested actions and return a refreshed execution plan");
    expect(readme).toContain("does not execute arbitrary shell commands");
    expect(readme).toContain("Applying accepted proposals refreshes derived graph relationships");
    expect(readme).toContain("matching raw source evidence");
    expect(readme).toContain("Raw source matches are included as secondary evidence");
    expect(readme).toContain("hybrid retrieval and reranking");
    expect(readme).toContain("lexical, vector, and rerank scores");
    expect(readme).toContain("local semantic baseline");
    expect(readme).toContain("source provenance");
    expect(readme).toContain("query results show source provenance");
    expect(readme).toContain("context and act outputs repeat source provenance beside each reviewed evidence item");
    expect(readme).toContain("suggested maintenance actions");
    expect(readme).toContain("notva review --vault");
    expect(readme).toContain("review cards show the source evidence");
    expect(readme).toContain("retrieve-then-act workflows");
    expect(readme).toContain("query result into a reviewable wiki proposal");
    expect(readme).toContain("notva concepts propose");
    expect(readme).toContain("## Agent Instructions");
    expect(readme).toContain("notva install --platform codex");
    expect(readme).toContain("notva install --platform codex --project");
    expect(readme).toContain("## Local Web Workbench");
  });

  test("provides a Chinese README for open-source users", async () => {
    const readme = await readFile(new URL("../README.zh-CN.md", import.meta.url), "utf8");

    expect(readme).toContain("# Notva");
    expect(readme).toContain("AI 维护的个人知识库");
    expect(readme).toContain("LLM Wiki");
    expect(readme).toContain("默认知识库路径是 `~/Notva`");
    expect(readme).toContain("notva ingest <file|directory|url>");
    expect(readme).toContain("notva review --apply all");
    expect(readme).toContain("notva query \"question\"");
    expect(readme).toContain("notva act \"task\"");
    expect(readme).toContain("图谱层");
    expect(readme).toContain("混合检索和重排");
    expect(readme).toContain("Provider 适配器");
    expect(readme).toContain("@notva/providers");
    expect(readme).toContain("发布边界");
    expect(readme).toContain("MIT");
    expect(readme).toContain("本地 Web 工作台");
  });
});
